##
## secret.example.yaml
## copy this file to scert.yaml and fill in the following information
## run `ts-node scripts/github-action-secret.ts` to upload secrets to github
##

## deploy to
DEPLOY_HOST:
DEPLOY_USERNAME:
DEPLOY_KEY: |

## github distpach workflow token
DISPATCH_TOKEN:

## feishu
FEISHU_ROBOT_TOKEN:

## aliyun
ALI_REGISTRY:
ALI_USERNAME:
ALI_PASSWORD:
