version: '3'
services:
  mongodb:
    restart: always
    image: mongo
    ports:
      - 27017:27017
  emqx:
    image: emqx/emqx
    ports:
      - 1883:1883
      - 8081:8081
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
  redis:
    image: redis/redis-stack-server
    ports:
      - 6379:6379
