export const ErrorCodes = {
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  EMPLOYEE_ID_ALREADY_EXISTS: 'EMPLOYEE_ID_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  PHONE_ALREADY_EXISTS: 'PHONE_ALREADY_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  WRONG_OLD_PASSWORD: 'WRONG_OLD_PASSWORD',
};
