export const ErrorCodes = {
  AUTH_FAILED: 'AUTH_FAILED',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  CAPTCHA_INVALID: 'CAPTCHA_INVALID',
  TOO_MANY_LOGIN_ATTEMPTS: 'TOO_MANY_LOGIN_ATTEMPTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  CAPTCHA_NOT_FOUND: 'CAPTCHA_NOT_FOUND',
  CASTERROR: 'CASTERROR',
  DUPLICATE: 'DUPLICATE',
  VALIDATE_FAILED: 'VALIDATION_FAILED',
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
  EMAIL_RECORD_NOT_FOUND: 'EMAIL_RECORD_NOT_FOUND',
  GROUP_ALREADY_EXISTS: 'GROUP_ALREADY_EXISTS',
  GROUP_NOT_FOUND: 'GROUP_NOT_FOUND',
  NAMESPACE_ALREADY_EXISTS: 'NAMESPACE_ALREADY_EXISTS',
  NAMESPACE_NOT_FOUND: 'NAMESPACE_NOT_FOUND',
  EMPLOYEE_ID_ALREADY_EXISTS: 'EMPLOYEE_ID_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  PHONE_ALREADY_EXISTS: 'PHONE_ALREADY_EXISTS',
  WRONG_OLD_PASSWORD: 'WRONG_OLD_PASSWORD',
  ROLE_ALREADY_EXISTS: 'ROLE_ALREADY_EXISTS',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SMS_SEND_FAILED: 'SMS_SEND_FAILED',
  SMS_RECORD_NOT_FOUND: 'SMS_RECORD_NOT_FOUND',
};

export const GithubAccessTokenUrl = 'https://github.com/login/oauth/access_token';
export const GithubClientId = 'Iv23lizBaVPIiABBCHaz';
export const GithubClientSecret = '041f46399c1396ec27d16851c1aa2aa479a3f5a5';
export const GithubUserUrl = 'https://api.github.com/user';
